name: Deploy to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'public/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        if: ${{ env.VERCEL_TOKEN != '' }}
        run: npx vercel deploy public/ --prod --yes --token $VERCEL_TOKEN
